run:
  timeout: 5m
  go: "1.24"
linters:
  disable:
    - errcheck
linters-settings:
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/sbchaos/opms
severity:
  default-severity: error