version: "2"
run:
  go: "1.24"
linters:
  disable:
    - errcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
formatters:
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/sbchaos/opms
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
